USE customer_behaviour;
SELECT * FROM customer;

-- Total revenue generated by male vs female customers

SELECT gender,
       SUM(`purchase_amount_(usd)`) AS revenue
FROM customer
GROUP BY gender;


DESCRIBE customer;

-- customers used discount but still spent more than a average purchase_amount

SELECT customer_id, `purchase_amount_(usd)`
FROM customer
WHERE discount_applied = "Yes" and `purchase_amount_(usd)` >= (SELECT AVG(`purchase_amount_(usd)`)); 

-- top 5 products with the highest average review rating

SELECT item_purchased, (AVG(review_rating)) AS "Average Product Rating"
FROM customer
GROUP BY  item_purchased
ORDER BY AVG(review_rating) DESC LIMIT 5;


-- compare the avg purchase amounts between standard and express shipping

SELECT shipping_type, ROUND(AVG(`purchase_amount_(usd)`),2)
FROM customer
WHERE shipping_type IN ('Standard','Express') 
GROUP BY shipping_type;

-- Compare avg spend and total revenue between subscribers and non subscribers


SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(`purchase_amount_(usd)`),2) AS avg_spend,
ROUND(SUM(`purchase_amount_(usd)`),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;

-- 5 products that have the highest percentage of purchases with discounts applied

SELECT item_purchased,
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) * 100,2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC LIMIT 5;

-- Segment customers into new, returning and loyal based on their total no. of previous purchases, and show the count of each segment


WITH customer_type AS(
SELECT customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer
)

SELECT customer_segment, COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment; 

-- 3 most purchased products within each category

WITH item_counts AS (
SELECT category, 
item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

-- are the cutomers who are repeat buyers (more than 5 previous purchases) also likely to subscribe

SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5 
GROUP BY subscription_status
ORDER BY repeat_buyers DESC;


-- revenue contribution of each age group

SELECT age_group,
SUM(`purchase_amount_(usd)`) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
 
USE customer_behaviour;
DESCRIBE customer;

SELECT age, age_group FROM customer LIMIT 10;
